name: 'CI'
on: workflow_dispatch
jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install python package
        run: |
          pip3 install --no-cache-dir -q -r requirements.txt --use-pep517
      - name: Run simple test
        run: |
          pytest -v -s  \
            --html=outputs/test_report.html --self-contained-html \
            --junitxml=outputs/test_report.xml \
            test_1.py
      - name: Upload test result
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: outputs/
          retention-days: 30
      - run: echo "🍏 This job's status is ${{ job.status }}."