name: test runner
on: push
jobs:
  E2E-Testing:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.35.0-jammy
    permissions:
      checks: write
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: ⭐ Run E2E testing docker
        run: |
          python -m pip install --upgrade pip
          pip install --root-user-action=ignore --no-cache-dir -r requirements.txt
          pytest --browser=firefox --device="Desktop Firefox" test_playwright.py
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: E2E Test Report
          path: outputs/test_report.xml
          reporter: java-junit
      - name: Upload test outputs
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-outputs
          path: outputs
