name: Test Playwright Container
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --root-user-action=ignore --no-cache-dir --upgrade pip
          pip install --root-user-action=ignore --no-cache-dir -r requirements.txt

      - name: Check python version
        run: python --version

      - name: Run your tests (by Firefox)
        run: HOME=/root pytest --device="Desktop Firefox" --browser=firefox test_playwright.py
      # - name: Run your tests (by Safari)
      #   run: pytest --device="Desktop Safari" --browser=webkit test_playwright.py
