name: Test Playwright Container
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    container:
      # image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
      image: python:3.12.3-slim
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --root-user-action=ignore --no-cache-dir --upgrade pip
          pip install --root-user-action=ignore --no-cache-dir -r requirements.txt
          playwright install --with-deps

      - name: Run your tests
        run: pytest --video=retain-on-failure --screenshot=only-on-failure --device="iPhone 14" --browser=webkit test_playwright.py

      - name: Upload test outputs
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
