name: Test Playwright Container
on: workflow_dispatch
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    container:
      image: mcr.microsoft.com/playwright/python:v1.34.0-jammy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --root-user-action=ignore --no-cache-dir --upgrade pip
      - name: Install dependencies \#2
        run: pip install --root-user-action=ignore --no-cache-dir -r requirements.txt
      # - name: Install dependencies \#3
      #   run: pip install -e .
      - name: Ensure browsers are installed
        run: playwright install firefox --with-deps
      - name: Run your tests
        run: pytest --device='Desktop Firefox' --browser=firefox test_playwright.py
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: outputs/test_report.xml
      - name: Upload test outputs
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-outputs
          path: outputs
